### ISSUE TITLE
Bold in Command Name

### ISSUE THREAD

**Issue by arfajaw** [fusebit/fusebot#26]
After adding the bot to slack I copied the command from the [bot-installed page](https://go.fusebit.io/fusebot-slack-installed/)
Pasting it to slack, the text is in bold. This throws an error

![image](https://user-images.githubusercontent.com/30311574/124806400-5246e180-df65-11eb-8003-27d239181251.png)

**Comment by chrismore** [comment]
@arfaj-a thanks for the file!

Can you try something for me?

Try running:

`/fusebot coin DOGE`

Without bold and let me know if you don't get an error.

Also, if you want to go back to the bot-installed page, refresh and try to copy/paste it now. See if the commands still come through as bold. 

Thanks!

Thanks!

**Comment by chrismore** [comment]
The same problem happens for italic and strikethrough text. Basically, any regular vs bolt vs italic vs strikethrough are all considered unique characters and thus the commands are unique. We're checking to see if we can stripe out any non-regular text formatting.

**Comment by arfajaw** [comment]
Upon further testing, it seems that formatting only affects the passed arguments. 

e.g.
**/fusebot coin** doge ✔️  
/fusebot coin **doge** ❌ 

The first two are Slack's responsibility handle :) 

Good Luck

**Comment by tjanczuk** [comment]
Thank you for the report @arfaj-a!

Fixed by removing the bold, italics, and strikethrough markup from the *command name* only (the `coin` part). The arguments that follow are under the control of the command code itself and it should be up to the command to either remove the markup from there or not depending on the desired semantics. 

So with this fix, the following should work: 

```
/fusebot *coin* doge
/fusebot _coin_ doge
/fusebot ~coin~ doge
```
The following will work as well, but in an unintended way: 
```
/fusebot *coin doge*
/fusebot _coin doge_
/fusebot ~coin doge~
```
The markup will be stripped from the `coin` command name and the command will be invoked, but the argument passed in will be `doge*`, `doge_`, or `doge~`, respectively. Since the command code does not strip markup from its arguments and the API it uses is designed to normalize all coin symbols it does not understand to bitcoin, the returned price will be that of bitcoin. 

@chrismore I believe a complete fix to this is to change the copy on the callback page so that either only the `coin` part is in bold, or the entire `/fusebot coin doge` is markup-free.

**Comment by chrismore** [comment]
@arfaj-a this should be all resolved now. Thanks for filing this and helping improve Fusebot for everyone. :-)
